kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-controller
  namespace: ${NAME_SPACE}
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
  client-max-body-size: "2m"
  worker-connections: "98765"
